import { StyleSheet } from "react-native";

export const screenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#eef0ff",
  },
  settingsScreen: {
    flex: 1,
    backgroundColor: "#f6f8ff",
  },
  settingsBackdropTop: {
    position: "absolute",
    top: -88,
    right: -40,
    width: 230,
    height: 230,
    backgroundColor: "#dbe7ff",
    borderRadius: 999,
    opacity: 0.95,
  },
  settingsBackdropBottom: {
    position: "absolute",
    bottom: -120,
    left: -80,
    width: 270,
    height: 270,
    backgroundColor: "#e8efff",
    borderRadius: 999,
  },
  chatScreen: {
    flex: 1,
    backgroundColor: "#f6f8ff",
  },
  chatBackdropTop: {
    position: "absolute",
    top: -84,
    right: -28,
    width: 224,
    height: 224,
    backgroundColor: "#dbe7ff",
    borderRadius: 999,
    opacity: 0.95,
  },
  chatBackdropBottom: {
    position: "absolute",
    bottom: -120,
    left: -70,
    width: 260,
    height: 260,
    backgroundColor: "#e8efff",
    borderRadius: 999,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 16,
  },
  chatHeroCard: {
    backgroundColor: "#1550ff",
    borderRadius: 28,
    overflow: "hidden",
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 20,
    shadowColor: "#1550ff",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
  },
  chatHeroEyebrow: {
    color: "#dbe7ff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  chatHeroTitle: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 34,
    marginTop: 8,
  },
  chatHeroBody: {
    color: "#edf3ff",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
    maxWidth: "88%",
  },
  chatTopicRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  chatTopicChip: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chatTopicChipText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  chatEmptyCard: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    gap: 12,
    padding: 22,
    shadowColor: "#16336d",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  chatEmptyTitle: {
    color: "#12213f",
    fontSize: 22,
    fontWeight: "800",
  },
  chatEmptyBody: {
    color: "#5b6882",
    fontSize: 14,
    lineHeight: 21,
  },
  chatPromptList: {
    gap: 10,
    marginTop: 6,
  },
  chatPromptChip: {
    backgroundColor: "#f7faff",
    borderColor: "#d8e3f6",
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  chatPromptChipText: {
    color: "#183153",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
  },
  chatList: {
    flex: 1,
  },
  chatListContent: {
    paddingBottom: 8,
  },
  chatTypingCard: {
    alignItems: "center",
    backgroundColor: "#eef4ff",
    borderColor: "#d9e5ff",
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  chatTypingDots: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 999,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  chatTypingTextWrap: {
    flex: 1,
    gap: 2,
  },
  chatTypingTitle: {
    color: "#12213f",
    fontSize: 14,
    fontWeight: "800",
  },
  chatTypingBody: {
    color: "#61708e",
    fontSize: 12,
    lineHeight: 18,
  },
  authScreen: {
    flex: 1,
    backgroundColor: "#f5f8ff",
    overflow: "hidden",
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  authGlowTop: {
    position: "absolute",
    top: -82,
    right: -36,
    width: 248,
    height: 248,
    backgroundColor: "#dbe7ff",
    borderRadius: 999,
    opacity: 0.95,
  },
  authGlowBottom: {
    position: "absolute",
    bottom: -126,
    left: -72,
    width: 280,
    height: 280,
    backgroundColor: "#d9e4ff",
    borderRadius: 999,
    opacity: 0.82,
  },
  authGlowCenter: {
    position: "absolute",
    top: "34%",
    right: -18,
    width: 160,
    height: 160,
    backgroundColor: "#ebf1ff",
    borderRadius: 999,
    opacity: 0.95,
  },
  authShell: {
    flex: 1,
    gap: 18,
  },
  authHero: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    gap: 14,
    marginTop: "auto",
    minHeight: 320,
    paddingHorizontal: 24,
    paddingBottom: 28,
    paddingTop: 24,
  },
  authHeroBand: {
    display: "none",
  },
  authHeroCloudLarge: {
    position: "absolute",
    bottom: -8,
    right: -12,
    width: 160,
    height: 160,
    backgroundColor: "#3d4ae0",
    borderRadius: 999,
  },
  authHeroCloudSmall: {
    position: "absolute",
    top: -22,
    left: -30,
    width: 112,
    height: 112,
    backgroundColor: "#e8ebff",
    borderRadius: 999,
  },
  authHeroLabel: {
    color: "#3d4ae0",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  authHeroTitle: {
    color: "#14143a",
    fontSize: 30,
    fontWeight: "700",
    lineHeight: 34,
    textAlign: "center",
  },
  authHeroBody: {
    color: "#45456a",
    fontSize: 14,
    lineHeight: 22,
    maxWidth: "88%",
    textAlign: "center",
  },
  authPoints: {
    gap: 10,
    marginTop: 18,
  },
  authPoint: {
    color: "#30305d",
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    backgroundColor: "#fffdfc",
    borderColor: "#eadeda",
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 20,
    shadowColor: "#1f2035",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  sectionHeader: {
    gap: 6,
  },
  eyebrow: {
    color: "#3d4ae0",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: {
    color: "#14143a",
    fontSize: 28,
    fontWeight: "700",
  },
  authCardTitle: {
    color: "#14143a",
    fontSize: 30,
    fontWeight: "700",
    textAlign: "center",
  },
  body: {
    color: "#5d5d78",
    fontSize: 15,
    lineHeight: 22,
  },
  meta: {
    color: "#2f3351",
    fontSize: 14,
  },
  field: {
    gap: 8,
  },
  label: {
    color: "#2b2f48",
    fontSize: 13,
    fontWeight: "600",
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#c9cad8",
    borderRadius: 12,
    borderWidth: 1,
    color: "#14143a",
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  inputHint: {
    color: "#6b7088",
    fontSize: 12,
    lineHeight: 18,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#3d4ae0",
    borderColor: "#3d4ae0",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  buttonText: {
    color: "#fff8f6",
    fontSize: 15,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d7d8e3",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: "#2f3351",
    fontSize: 15,
    fontWeight: "700",
  },
  error: {
    color: "#b91c1c",
    fontSize: 13,
  },
  listContent: {
    paddingBottom: 20,
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#1550ff",
    borderRadius: 22,
    borderTopRightRadius: 8,
    marginBottom: 14,
    maxWidth: "85%",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  assistantBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderColor: "#dbe3f2",
    borderRadius: 22,
    borderTopLeftRadius: 8,
    borderWidth: 1,
    marginBottom: 14,
    maxWidth: "85%",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  bubbleRole: {
    color: "#7a86a2",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  bubbleText: {
    color: "#14143a",
    fontSize: 15,
    lineHeight: 22,
  },
  userBubbleText: {
    color: "#fff8f6",
    fontSize: 15,
    lineHeight: 22,
  },
  dividerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  dividerLine: {
    backgroundColor: "#e5dcda",
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: "#777b93",
    fontSize: 13,
  },
  socialRow: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "center",
  },
  socialButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d5df",
    borderRadius: 12,
    borderWidth: 1,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  socialButtonText: {
    color: "#2f3351",
    fontSize: 22,
    fontWeight: "700",
  },
  footerText: {
    color: "#5d5d78",
    fontSize: 14,
    textAlign: "center",
  },
  footerAction: {
    color: "#14143a",
    fontWeight: "700",
  },
  onboardingViewport: {
    flex: 1,
  },
  onboardingPage: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 24,
    paddingHorizontal: 18,
    paddingTop: 22,
  },
  onboardingTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    minHeight: 20,
  },
  onboardingTopLabel: {
    color: "#1550ff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  onboardingSkip: {
    color: "#6c7597",
    fontSize: 13,
    fontWeight: "700",
  },
  onboardingArt: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    minHeight: 280,
  },
  onboardingArtHalo: {
    position: "absolute",
    width: 288,
    height: 288,
    borderRadius: 999,
    backgroundColor: "#e8f0ff",
  },
  onboardingArtBubble: {
    alignItems: "center",
    backgroundColor: "#1550ff",
    borderRadius: 132,
    height: 244,
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#1550ff",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.22,
    shadowRadius: 28,
    width: 244,
  },
  onboardingArtGlow: {
    position: "absolute",
    top: 18,
    right: -12,
    width: 110,
    height: 110,
    borderRadius: 999,
    backgroundColor: "#5e8bff",
    opacity: 0.34,
  },
  onboardingArtAccent: {
    position: "absolute",
    bottom: 16,
    right: 20,
    width: 68,
    height: 68,
    borderRadius: 999,
    backgroundColor: "#7ba2ff",
    opacity: 0.35,
  },
  onboardingArtAccentSoft: {
    position: "absolute",
    left: -16,
    bottom: 36,
    width: 94,
    height: 94,
    borderRadius: 999,
    backgroundColor: "#5e8bff",
    opacity: 0.2,
  },
  onboardingIllustration: {
    color: "#ffffff",
    fontSize: 88,
    fontWeight: "800",
  },
  onboardingCard: {
    backgroundColor: "#ffffff",
    borderRadius: 30,
    minHeight: 364,
    paddingHorizontal: 24,
    paddingTop: 26,
    paddingBottom: 22,
    shadowColor: "#16336d",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  onboardingEyebrow: {
    color: "#1550ff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  onboardingTitle: {
    color: "#12213f",
    fontSize: 31,
    fontWeight: "800",
    lineHeight: 36,
    marginTop: 10,
  },
  onboardingDescription: {
    color: "#576684",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
  },
  onboardingFeaturePill: {
    alignSelf: "flex-start",
    backgroundColor: "#eef4ff",
    borderRadius: 999,
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  onboardingFeaturePillText: {
    color: "#1550ff",
    fontSize: 12,
    fontWeight: "700",
  },
  onboardingPreview: {
    backgroundColor: "#f7faff",
    borderColor: "#dce7ff",
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    marginTop: 18,
    padding: 16,
  },
  onboardingPreviewHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  onboardingPreviewAvatar: {
    alignItems: "center",
    backgroundColor: "#1550ff",
    borderRadius: 999,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  onboardingPreviewAvatarText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  onboardingPreviewTitleWrap: {
    flex: 1,
    gap: 2,
  },
  onboardingPreviewLabel: {
    color: "#12213f",
    fontSize: 14,
    fontWeight: "700",
  },
  onboardingPreviewMeta: {
    color: "#6f7b95",
    fontSize: 12,
  },
  onboardingPreviewQuestion: {
    color: "#12213f",
    fontSize: 14,
    fontWeight: "700",
  },
  onboardingPreviewAnswer: {
    color: "#576684",
    fontSize: 13,
    lineHeight: 20,
  },
  paginationRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-start",
    marginTop: 18,
    marginBottom: 18,
  },
  paginationDot: {
    backgroundColor: "#d2dcf5",
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  paginationDotActive: {
    backgroundColor: "#1550ff",
    width: 26,
  },
  onboardingButton: {
    alignItems: "center",
    backgroundColor: "#1550ff",
    borderRadius: 16,
    justifyContent: "center",
    minHeight: 54,
    shadowColor: "#1550ff",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  onboardingButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  loginScreenContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 22,
  },
  authCard: {
    backgroundColor: "#ffffff",
    borderRadius: 30,
    marginTop: -12,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
    shadowColor: "#16336d",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  authHeaderPanel: {
    backgroundColor: "#1550ff",
    borderRadius: 32,
    minHeight: 178,
    overflow: "hidden",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
  },
  authHeaderOrbLeft: {
    position: "absolute",
    left: -30,
    top: 76,
    width: 132,
    height: 132,
    borderRadius: 999,
    backgroundColor: "#7ba2ff",
    opacity: 0.92,
  },
  authHeaderOrbRight: {
    position: "absolute",
    right: -38,
    top: -14,
    width: 156,
    height: 156,
    borderRadius: 999,
    backgroundColor: "#d8e6ff",
    opacity: 0.34,
  },
  authHeaderOrbSoft: {
    position: "absolute",
    right: 28,
    bottom: -20,
    width: 118,
    height: 118,
    borderRadius: 999,
    backgroundColor: "#94b0ff",
    opacity: 0.32,
  },
  authHeaderEyebrow: {
    color: "#dce7ff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  authHeaderTitle: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 34,
    marginTop: 8,
  },
  authHeaderBody: {
    color: "#edf3ff",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
    maxWidth: "74%",
  },
  authPanelWrap: {
    flex: 1,
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  authStage: {
    minHeight: 166,
    position: "relative",
  },
  authActionRow: {
    flexDirection: "row",
    gap: 12,
  },
  authHalfButton: {
    flex: 1,
  },
  authPanelScroll: {
    flex: 1,
  },
  authPanelContent: {
    flexGrow: 1,
    gap: 14,
    paddingBottom: 18,
  },
  floatingLabel: {
    color: "#20304f",
    fontSize: 12,
    fontWeight: "700",
  },
  authInput: {
    backgroundColor: "#f8fbff",
    borderColor: "#bccae4",
    borderRadius: 16,
    borderWidth: 1,
    color: "#12213f",
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  authGoogleButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d7d8e3",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "center",
    minHeight: 56,
  },
  authGoogleMark: {
    color: "#3d4ae0",
    fontSize: 24,
    fontWeight: "800",
  },
  authGoogleText: {
    color: "#2f3351",
    fontSize: 16,
    fontWeight: "600",
  },
  authSplitFieldRow: {
    flexDirection: "row",
    gap: 10,
  },
  authSplitField: {
    flex: 1,
  },
  authPasswordRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 0,
  },
  authPasswordInput: {
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    flex: 1,
  },
  authPasswordToggle: {
    alignItems: "center",
    backgroundColor: "#eff5ff",
    borderColor: "#d8e3f6",
    borderBottomRightRadius: 16,
    borderLeftWidth: 0,
    borderTopRightRadius: 16,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: 16,
  },
  authPasswordToggleText: {
    color: "#1550ff",
    fontSize: 13,
    fontWeight: "700",
  },
  authPrimaryButton: {
    alignItems: "center",
    backgroundColor: "#1550ff",
    borderRadius: 18,
    justifyContent: "center",
    minHeight: 50,
    shadowColor: "#1550ff",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  authPrimaryButtonPressed: {
    opacity: 0.92,
  },
  authButtonLoadingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  authPrimaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  authPreviewButton: {
    alignItems: "center",
    alignSelf: "center",
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  authPreviewButtonText: {
    color: "#5d6d8e",
    fontSize: 13,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  authFormBlock: {
    gap: 14,
  },
  authSecondaryRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "space-between",
    marginTop: 4,
    marginBottom: 10,
  },
  authSecondaryHint: {
    color: "#6b7088",
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 18,
    paddingRight: 12,
  },
  authSecondaryLink: {
    color: "#1550ff",
    fontSize: 13,
    fontWeight: "700",
  },
  authLegalText: {
    color: "#6b7891",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 14,
    textAlign: "center",
  },
  authLegalAction: {
    color: "#12213f",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  authBottomPrompt: {
    color: "#2d3b57",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 18,
    textAlign: "center",
  },
  authBottomAction: {
    color: "#0f172a",
    fontWeight: "800",
    textDecorationLine: "underline",
  },
  authBottomMuted: {
    color: "#2d3b57",
    fontWeight: "700",
  },
  authSpacer: {
    flex: 1,
    minHeight: 12,
  },
  composer: {
    gap: 10,
  },
  chatComposerCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    gap: 10,
    padding: 16,
    shadowColor: "#16336d",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  chatComposerLabel: {
    color: "#12213f",
    fontSize: 13,
    fontWeight: "800",
  },
  composerInput: {
    backgroundColor: "#f8fbff",
    borderColor: "#cad6eb",
    borderRadius: 16,
    borderWidth: 1,
    color: "#14143a",
    maxHeight: 120,
    minHeight: 96,
    padding: 14,
    textAlignVertical: "top",
  },
  chatShortcutRow: {
    flexDirection: "row",
    gap: 8,
  },
  chatShortcutChip: {
    backgroundColor: "#f4f7ff",
    borderColor: "#dbe4f6",
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  chatShortcutChipText: {
    color: "#42516e",
    fontSize: 11,
    fontWeight: "700",
  },
  chatComposerFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  chatComposerHint: {
    color: "#6b7891",
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
  },
  chatSendButton: {
    alignItems: "center",
    backgroundColor: "#1550ff",
    borderRadius: 16,
    justifyContent: "center",
    minHeight: 46,
    minWidth: 88,
    paddingHorizontal: 18,
  },
  chatSendButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  chatSendButtonDisabled: {
    opacity: 0.7,
  },
  chatSendButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  settingsHeroCard: {
    backgroundColor: "#1550ff",
    borderRadius: 28,
    gap: 18,
    padding: 22,
    shadowColor: "#1550ff",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
  },
  settingsProfileRow: {
    flexDirection: "row",
    gap: 14,
  },
  settingsAvatar: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 22,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  settingsAvatarText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  settingsProfileCopy: {
    flex: 1,
    gap: 4,
  },
  settingsEyebrow: {
    color: "#dbe7ff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  settingsTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "800",
  },
  settingsBody: {
    color: "#edf3ff",
    fontSize: 14,
    lineHeight: 21,
  },
  settingsMetaRow: {
    flexDirection: "row",
    gap: 10,
  },
  settingsMetaChip: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  settingsMetaLabel: {
    color: "#dbe7ff",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  settingsMetaValue: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  settingsSectionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    gap: 10,
    padding: 18,
    shadowColor: "#16336d",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  settingsSectionTitle: {
    color: "#12213f",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
  },
  settingsActionRow: {
    alignItems: "center",
    backgroundColor: "#f8fbff",
    borderColor: "#dbe4f6",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  settingsActionIcon: {
    alignItems: "center",
    backgroundColor: "#eef4ff",
    borderRadius: 14,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  settingsActionCopy: {
    flex: 1,
    gap: 2,
  },
  settingsActionTitle: {
    color: "#12213f",
    fontSize: 14,
    fontWeight: "800",
  },
  settingsActionBody: {
    color: "#62718d",
    fontSize: 12,
    lineHeight: 18,
  },
  settingsDangerButton: {
    alignItems: "center",
    backgroundColor: "#0f172a",
    borderRadius: 18,
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    minHeight: 50,
  },
  settingsDangerButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  tabBar: {
    backgroundColor: "#fffdfc",
    borderTopColor: "#eadeda",
    height: 68,
    paddingBottom: 8,
    paddingTop: 8,
  },
  header: {
    backgroundColor: "#eef0ff",
  },
  headerTitle: {
    color: "#14143a",
    fontSize: 17,
    fontWeight: "700",
  },
  appHeaderTitleWrap: {
    gap: 1,
  },
  appHeaderEyebrow: {
    color: "#6b7a98",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  appHeaderTitle: {
    color: "#12213f",
    fontSize: 17,
    fontWeight: "800",
  },
  appHeaderProfile: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  appHeaderProfileTextWrap: {
    alignItems: "flex-end",
    maxWidth: 110,
  },
  appHeaderProfileName: {
    color: "#12213f",
    fontSize: 13,
    fontWeight: "700",
  },
  appHeaderProfileMeta: {
    color: "#6b7a98",
    fontSize: 11,
    fontWeight: "600",
  },
  appHeaderAvatar: {
    alignItems: "center",
    backgroundColor: "#1550ff",
    borderRadius: 999,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  appHeaderAvatarText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
});
